Fix get_table_oid in HANAInspector to also work with inspectors created from Engine instances
SAP/sqlalchemy-hana pull request #242
Opened 2024-04-20 10:04 UTC by Masterchen09

Similar to the issue for the built-in PostgreSQL dialect resp. the corresponding PGInspector class (https://github.com/sqlalchemy/sqlalchemy/issues/6170) the get_table_oid method of the HANAInspector cannot be used when the inspector was created using the Engine instance and not a Connection instance.

This PR fixes this using the same solution from the PGInspector class (see also here for details: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2697).

2024-04-20 10:12 UTC, kasium commented
Thanks for the contribution. A test is required to merge this. Could you please add one? Else I'll take a look next week

2024-04-20 12:31 UTC, Masterchen09 commented
I have added a test - as there aren't any tests for the other inspector methods (e.g., get_schema_names, get_table_names, ...), I have tried to use the SelectTest (for creating a table) and the DialectTest (for creating the engine instance) as examples...as I have currently no database available to test it myself, I am not sure whether it works or not - we will see when the workflow is running.

2024-04-20 18:35 UTC, kasium commented
Seems like there is a CI issue. Let me check this later

2024-04-22 13:48 UTC, Masterchen09 commented
The CI pipeline is working now, but according to the log the test_inspector.py was not executed during tests...and I have absolutely no idea why...😅

2024-04-22 14:03 UTC, kasium commented
> The CI pipeline is working now, but according to the log the test_inspector.py was not executed during tests...and I have absolutely no idea why...😅

I see. Let me check this later

2024-04-23 05:27 UTC, kasium requested changes

2024-04-23 05:27 UTC, kasium commented on test/test_inspector.py
> +        eng = create_engine(config.db.url)
create_engine is not defined

2024-04-23 05:47 UTC, kasium requested changes

2024-04-23 05:47 UTC, kasium commented on test/test_inspector.py
> +        table_oid1 = connection_inspector.get_table_oid(self.tables.tbl)
fails with

```
test/test_inspector.py::InspectorTest::test_get_table_oid - AttributeError: 'Table' object has no attribute 'lower'
```

2024-04-23 05:50 UTC, kasium commented
@Masterchen09 executing the test locally fails but at least it is found. I guess that the wrong SHA was checked out. Please update once again to the lastest main and let the CI again run

2024-04-23 16:02 UTC, Masterchen09 commented
@kasium After rebasing the test_inspector.py is also executed...strange...😅

After some adjustments (the import for the Connection and Engine from sqlalchemy instead of sqlalchemy.engine was also not working for version 1.4) the tests are now passing - except one check: As I have copied the define_tables method from test_select.py...the pre-commit check is reporting it as duplicated code now - I am not sure whether duplicated code is a "big" issue in tests and should be reported (of course it would also be possible to create a different example, but it really doesn't matter? 🤷‍♂️)...

2024-04-24 05:06 UTC, kasium commented
@Masterchen09 feel free to add `"duplicate-code"` to the `[tool.pylint."messages control"]` section (key `disable`) in `pyproject.toml`. I'll improve this later

2024-04-25 05:55 UTC, kasium approved these changes

2024-04-25 05:55 UTC, merged